# Permalinks
permalink:           blog/:title

# Setup
title:               Alexey Guzey
url:                 http://guzey.com
paginate:            10
paginate_path: 	     "/blog/page:num"

author:
  name:              Alexey Guzey
  url:               https://twitter.com/alexeyguzey
  email:             alexey@guzey.com

# Menu
pages_list:
  Blog: '/blog'
  Feed: '/atom.xml'
  Blog Archive + Site Contents: '/site-contents'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist

highlighter: rouge
markdown: kramdown

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
  
# only shows posts' excepts in /blog/
excerpt_separator: "<!--excerpt-->"