# Permalinks
permalink:           /blog/:title

# Setup
title:               Alex Guzey
url:                 http://guzey.com
paginate:            5
paginate_path: 	     "blog/page:num"

author:
  name:              Alex Guzey
  url:               https://twitter.com/alex_guzey
  email:             alex@guzey.com

# Menu
pages_list:
  Insight Porn: '/insight'
  Blog: '/blog'
  Feed: '/atom.xml'
  Site Contents: '/site-contents'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

highlighter: rouge
markdown: kramdown

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
  
# only shows posts' excepts in /blog/
excerpt_separator: "<!--excerpt-->"